"""Content quality and anti-slop patterns used by the gate.

These should eventually be expanded into configurable rule packs sourced from
the marketing skill references.
"""

AI_SLOP_PHRASES = [
    "additionally",
    "as an ai language model",
    "align with",
    "all in all",
    "at the end of the day",
    "breathtaking",
    "buying journey",
    "commendable",
    "crucial",
    "curated",
    "delving into",
    "delve",
    "discover the world of",
    "ecosystem",
    "embark",
    "endless possibilities",
    "enhance",
    "ever-evolving",
    "fostering",
    "garner",
    "game-changing",
    "intricate",
    "intricacies",
    "in today's fast-paced world",
    "landscape",
    "leverage",
    "look no further",
    "meticulous",
    "multifaceted",
    "must-have",
    "nestled",
    "nuanced",
    "on the other hand",
    "paradigm",
    "paramount",
    "pivotal",
    "profound",
    "realm",
    "renowned",
    "robust",
    "seamless",
    "showcase",
    "stunning",
    "synergy",
    "tapestry",
    "testament",
    "transformative",
    "unlock",
    "underscore",
    "utilize",
    "valuable",
    "vibrant",
    "versatile",
    "whilst",
    "holistic",
    "comprehensive",
    "innovative",
    "cutting-edge",
    "in conclusion",
    "future outlook",
    "future looks bright",
    "exciting times",
    "it is important to note",
    "based on available information",
    "while specific details are limited"
]

AI_FORMULA_PATTERNS = [
    "stands as",
    "serves as",
    "is a testament",
    "is designed to",
    "pivotal moment",
    "setting the stage",
    "deeply rooted",
    "boasts a",
    "commitment to",
    "not only",
    "but also",
    "not just",
    "it's not just",
    "from * to *",
    "despite these challenges",
    "future outlook",
    "continues to thrive",
    "future looks bright",
    "exciting times",
    "this article will",
    "i hope this helps",
    "of course",
    "certainly",
    "great question",
    "let's explore",
    "as of",
    "while specific details are limited",
    "based on available information",
    "the following sections",
    "in this guide",
    "rule of three",
    "not only * but also *"
]

HELPFUL_CONTENT_SIGNALS = [
    "audience usefulness",
    "first-hand experience",
    "depth of knowledge",
    "satisfying answer",
    "original value",
    "trust and evidence",
    "answer-first",
    "decision support",
    "verified facts",
    "contextual internal links",
    "external references",
    "search-intent faq"
]

# Backward-compatible alias for earlier typoed import.
AI_SLop_PHRASES = AI_SLOP_PHRASES
